name: Api CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
        run: |
          MONGO_URI=$MONGO_URI MONGO_DATABASE=$MONGO_DATABASE 
          AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY AWS_S3_SECRET_KEY=$AWS_S3_SECRET_KEY 
          CLIENT_URL=$CLIENT_URL 
          ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
        run: |
          MONGO_URI=$MONGO_URI MONGO_DATABASE=$MONGO_DATABASE 
          AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY AWS_S3_SECRET_KEY=$AWS_S3_SECRET_KEY 
          CLIENT_URL=$CLIENT_URL 
          ./gradlew build -x test